### ISSUE TITLE
Terminating nvidia-pstated leaves GPU in low power state

### ISSUE THREAD

**Issue by LoopControl** [sasha0552/nvidia-pstated#1]
It seems that if I exit the app with a Control-C to end it, it leaves the GPU stuck in the lower power mode (p8).

Exiting the program should restore the GPU's automatic power management.

**Comment by sasha0552** [comment]
Implemented in https://github.com/sasha0552/nvidia-pstated/commit/abd799309bef3c0508556c4ace730d0ffd60bb5c (tag v1.0.3)
