### ISSUE TITLE
GPU compatibility 

### ISSUE THREAD

**Issue by Fuckingnameless** [sasha0552/nvidia-pstated#2]
which pascal GPUs can use this?

**Comment by sasha0552** [comment]
Theoretically, support is not limited to Pascal. All GPUs with more than one performance state (memory clock) are supported, including consumer GPUs.

To determine this, you can use `nvidia-smi -q -d SUPPORTED_CLOCKS`.

The performance state is actually the memory clock, so if you have more than one, everything should work. Although the performance state may not be 0 but, for example, 1.

You can override the performance state numbers with `--performance-state-high` and `--performance-state-low`.

E.g. for P40:
```
GPU 00000000:00:00.0
    Supported Clocks
 !      Memory                            : 3615 MHz      <-- pstate 0
            Graphics                      : 1531 MHz
            ...
            Graphics                      : 544 MHz
 !      Memory                            : 405 MHz       <-- pstate 8
            Graphics                      : 544 MHz
```
